fill layer with conditions
Vizzuality/web-mapping-workshop pull request #18
Opened 2022-12-23 10:53 UTC by mluena

This PR adds a consitional expression for geojson layers

2022-12-23 12:24 UTC, anamontiaga approved these changes

2023-01-16 10:25 UTC, mbarrenechea requested changes

2023-01-16 10:25 UTC, mbarrenechea commented on src/exercises/geojson/polygons/05.stories.tsx
> +border = '#000000';
border, opacity and hover should be removed from this one

2023-01-17 12:45 UTC, mbarrenechea approved these changes

2023-01-17 12:45 UTC, merged